[package]
name = "wmenu"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
arc-swap = "1.9.1"
directories = "6.0.0"
eframe = { version = "0.34.2", default-features = false, features = ["glow", "default_fonts", "accesskit", "wayland", "x11"] }
lnk = "0.6.4"
nucleo-matcher = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "1.1.2"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
windows = { version = "0.62.2", features = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
